### PR TITLE
Made header and footer into it's own scss document

### PR DESCRIPTION
**Pull request by EmilioSanchezLernia**
As per request I made the header and footer styling into it's own scss file to more easily be imported to the challenges page.

### CODE REVIEW

**Comment by MatsJoh50** [comment]
Im thinking that we should break it down even further, as to header.scss and footer.scss and not only "frame.scss"

Thats my only opition, great work!

**Comment by EmilioSanchezLernia** [comment]
> Im thinking that we should break it down even further, as to header.scss and footer.scss and not only "frame.scss"
> 
> Thats my only opition, great work!

I made them into seperate scss files as per requested 👍

**Review by MatsJoh50 — APPROVED** [review]
I like it!

**Comment by AnnaLenaO** [comment]
Good job! It makes it easier to read the code.

**Review by AnnaLenaO — APPROVED** [review]

**Pull request merged**
