### PR TITLE
also added booking.scss. Removed required pattern phoneNr

### PR DESCRIPTION
**Pull request by AnnaLenaO**
Added missing booking.scss. Removed required pattern for phoneNr to avoid message in modal 3 when booking confirmed. Phone number is not a factor in the POST request.

### CODE REVIEW

**Comment by AnnaLenaO** [comment]
Merge after testing and feedback.

**Comment by AnnaLenaO** [comment]
Can be merged.

**Review by EmilioSanchezLernia — CHANGES_REQUESTED** [review]
Please add a scroll to the modal cause I can't see the booking button otherwise

**Comment by AnnaLenaO** [comment]
> Please add a scroll to the modal cause I can't see the booking button otherwise

Fixed :)

**Review by EmilioSanchezLernia — APPROVED** [review]
It's working as intended now. Great job Anna-Lena 😄

**Pull request merged**
